module.exports = {
  ERROR : ":frowning2: Une erreur inconnue est survenue...",
  JOIN : "Bonjour jeune voyageur, et bienvenue sur le serveur RP !",
  NAN : ":frowning2: L'argument donné n'est pas un nombre !",
  DM_BLOCK: ":frowning2: Malheureusement, j'ai l'impression que vous n'êtes pas dans un serveur Discord...",
  CHANNEL_INVALID : ":frowning2: Le channel n'existe pas !",
  CHANNEL_PERM : ":key2: Je ne peux pas te laisser rentrer dans ce lieu !",
  ALIAS_INVALID : ":frowning2: Le nom de votre alias est incorect...",
  ALIAS_MODIFY : ":tools: L'alias du channel %1 est %2.",
  ALIAS_EXIST : ":frowning2: Vous avez déjà créé une entrée avec cet alias.",
  ALIAS_REMOVE : ":tools: L'alias \"%1\" a bien été supprimé.",
  ALIAS_NOBODY : ":frowning2: Vous avez aucune entrée avec cette alias...",
  ROLE_INVALID : ":frowning2: Le role n'existe pas !",
  ROLE_DEFINE : ":tools: Le rôle %1 à été défini pour le channel : %2",
  ROLE_MODIFY : ":tools: Le rôle %1 à été modifé pour le channel : %2",
  LOG_MOVE : "Changement de channel (RP)",
  MONEY_START : "%1 vous donne à tire exceptionnel %2 pour commencer votre aventure",
  MONEY_NOBODY_OTHER : ":frowning2: Aucun compte au nom de %1 n'existe...",
  MONEY_NOBODY : ":frowning2: Aucun compte à votre nom n'existe...",
  MONEY_START_ADMIN : ":dollar: %1 commencera avec %2 sur son compte",
  MONEY_REMOVE :":dollar: %1 a maintenant %2 de moins sur son compte",
  MONEY_ADD : ":dollar: %1 a maintenant %2 de plus sur son compte",
  MONEY_BALANCE_ADMIN :":dollar: %1 a %2 sur son compte",
  MONEY_BALANCE :"Vous avez %1 dans votre bourse",
  MONEY_BUY : "Vous recevez %1 dans votre bourse de %2",
  MONEY_SELL : "Vous donnez %1 à la bourse de %2",
  MONEY_NEGATIVE_ADMIN : ":warning: Le compte de %1 ne peux pas être négatif avant sa création ! En cas de force majeur, contactez-moi : <@140123457001226241>",
  USER_INVALID : ":frowning2: L'utilisateur n'existe pas !",
};