module.exports = {
    ERROR : ":frowning2: Une erreur inconnue est survenue...",
    JOIN : "\u200B      Bonjour jeune voyageur, et bienvenue sur le serveur RP Raenias, je suis le Gardiens Des Clefs de Libertown et aussi votre assistant. Pour bien débuter, je vous conseil de lire les règles que vous acceptez bien évidement. Par la suite, je vous encourage à prendre connaissance de l'histoire de Raenias (<#495509529719603211>).\n\n     Raenias compte 5 grandes races ainsi que le peuple des humains géré par le grand <@436431337944252417> qui est le Chancelier de Libertown ! Je vais maintenant vous parler des autres classes !\n\n     Pour avoir la liste des différents roles, allez dans le channel <#556397156030742528>. Pour vous faire une bonne idée de la meilleure faction, lisez les channels sur l'histoire, les sous-races ainsi que le chef de chaque faction.\n\n     Une fois l'histoire de Raenias sur le bout des doigt, vous pourrez commencer l'élaboration de votre fiche. Le Chroniqueur vous a commencer le travail en vous expliquant ce système !\n\n     Enfin, quand le moment sera venu, je vous assisterez dans la création de votre fiche. Pour m'avertir, envoyez moi simplement `J'adore Raenias !+`",
    NAN : ":frowning2: L'argument donné n'est pas un nombre !",
    ARGUMENT_NOBODY : ":frowning2: L'argument %1 n'existe pas...",
    TEST_MSG_NOBODY : ":frowning2: [TEST] Le message demandé n'existe pas...",
    DM_BLOCK: ":frowning2: Malheureusement, j'ai l'impression que vous n'êtes pas dans un serveur Discord...",
    DM_SEND : ":mailbox_with_mail: Je vous est envoyé un DM !",
    CHANNEL_INVALID : ":frowning2: Le channel n'existe pas !",
    CHANNEL_PERM : ":key2: Je ne peux pas te laisser rentrer dans ce lieu !",
    ALIAS_INVALID : ":frowning2: Le nom de votre alias est incorrect...",
    ALIAS_MODIFY : ":tools: L'alias du channel %1 est %2.",
    ALIAS_EXIST : ":frowning2: Vous avez déjà créé une entrée avec cet alias.",
    ALIAS_REMOVE : ":tools: L'alias \"%1\" a bien été supprimé.",
    ALIAS_NOBODY : ":frowning2: Vous avez aucune entrée avec cette alias...",
    ALIAS_CHANNEL_NOBODY : ":frowning2: Vous avez aucune entrée avec ce salon...",
    ALIAS_LIST : ":tools: Voici tous les alias pour ce salon :",
    ROLE_INVALID : ":frowning2: Le role n'existe pas !",
    ROLE_DEFINE : ":tools: Le rôle %1 à été défini pour le channel : %2",
    ROLE_MODIFY : ":tools: Le rôle %1 à été modifié pour le channel : %2",
    LOG_MOVE : "Changement de channel (RP)",
    MONEY_START : "%1 vous donne à tire exceptionnel %2 pour commencer votre aventure",
    MONEY_NOBODY_OTHER : ":frowning2: Aucun compte au nom de %1 n'existe...",
    MONEY_NOBODY : ":frowning2: Aucun compte à votre nom n'existe...",
    MONEY_START_ADMIN : ":dollar: %1 commencera avec %2 sur son compte",
    MONEY_REMOVE :":dollar: %1 a maintenant %2 de moins sur son compte",
    MONEY_ADD : ":dollar: %1 a maintenant %2 de plus sur son compte",
    MONEY_BALANCE_ADMIN :":dollar: %1 a %2 sur son compte",
    MONEY_BALANCE :"Vous avez %1 dans votre bourse",
    MONEY_BUY : "Vous recevez %1 dans votre bourse de %2",
    MONEY_SELL : "Vous donnez %1 à la bourse de %2",
    MONEY_NEGATIVE_ADMIN : ":warning: Le compte de %1 ne peux pas être négatif avant sa création ! En cas de force majeur, contactez-moi : <@140123457001226241>",
    USER_INVALID : ":frowning2: L'utilisateur n'existe pas !",
};